# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  apt_packages :
    - maven
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - rm trustyai/dep/org/trustyai/*
      - git clone https://github.com/trustyai-explainability/trustyai-explainability.git
      - mvn install package -DskipTests -f trustyai-explainability/explainability-core/pom.xml -Pshaded
      - mv trustyai-explainability/explainability-core/target/explainability-core-2.0.0-SNAPSHOT.jar trustyai/dep/org/trustyai/
      - mv trustyai-explainability/explainability-core/target/explainability-core-2.0.0-SNAPSHOT-tests.jar trustyai/dep/org/trustyai/
      - mvn compile package -DskipTests -f java_sources/trusty-ai-arrow/pom.xml
      - mv java_sources/trusty-ai-arrow/target/arrow-converters-0.0.1.jar trustyai/dep/org/trustyai/
    post_build:
      - rm -Rf trustyai-explainability

# install the package
python:
  install:
    - requirements: requirements-dev.txt
    - method: pip
      path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
