name: Build exp-core JAR
runs:
  using: "composite"
  steps:
    - name: Build exp-core
      shell: bash
      run: |
        git clone https://github.com/trustyai-explainability/trustyai-explainability.git
        mvn install package -DskipTests -f trustyai-explainability/explainability-core/pom.xml -Pshaded
        mv trustyai-explainability/explainability-core/target/explainability-core-*.jar trustyai/dep/org/trustyai/
        