name: Publish to PyPI
on:
  release:
    types: [ published ]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build explainability-core
        uses: ./.github/actions/build-core
      - name: Build arrow-converter
        uses: ./.github/actions/build-arrow-converter
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}