name: Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
          check-latest: true
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build explainability-core
        uses: ./.github/actions/build-core
      - name: Build arrow-converter
        uses: ./.github/actions/build-arrow-converter
      - name: Install TrustyAI Python package
        run: |
          pip install -r requirements-dev.txt
          pip install .
      - name: Lint
        run: |
          pylint --ignore-imports=yes $(find src/trustyai -type f -name "*.py")
      - name: Test with pytest
        run: |
          pytest -v -s tests/general
          pytest -v -s tests/initialization --forked
      - name: Style
        run: |
          black --check $(find src/trustyai -type f -name "*.py")
