name: Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
          check-latest: true
      - uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.5.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python setup.py build install
      - name: Lint
        run: |
          pylint --ignore-imports=yes $(find trustyai -type f -name "*.py")
      - name: Test with pytest
        run: |
          pytest -v
      - name: Style
        run: |
          black --check $(find trustyai -type f -name "*.py")
